-- Add missing columns to questionnaires table for full 11-section coverage
ALTER TABLE public.questionnaires
ADD COLUMN IF NOT EXISTS tagline text,
ADD COLUMN IF NOT EXISTS vision_statement text,
ADD COLUMN IF NOT EXISTS core_values text,
ADD COLUMN IF NOT EXISTS business_overview text,
ADD COLUMN IF NOT EXISTS brand_personality text,
ADD COLUMN IF NOT EXISTS brand_fonts text,
ADD COLUMN IF NOT EXISTS secondary_audience text,
ADD COLUMN IF NOT EXISTS customer_sources text,
ADD COLUMN IF NOT EXISTS best_sellers text,
ADD COLUMN IF NOT EXISTS seasonal_offerings text,
ADD COLUMN IF NOT EXISTS integrations_needed text,
ADD COLUMN IF NOT EXISTS future_addons text,
ADD COLUMN IF NOT EXISTS open_to_stock boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS existing_marketing text,
ADD COLUMN IF NOT EXISTS target_locations text,
ADD COLUMN IF NOT EXISTS has_google_business boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS wants_ongoing_seo boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS compliance_needs text,
ADD COLUMN IF NOT EXISTS liked_websites text,
ADD COLUMN IF NOT EXISTS disliked_websites text,
ADD COLUMN IF NOT EXISTS design_elements text,
ADD COLUMN IF NOT EXISTS needs_email boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS expected_traffic text,
ADD COLUMN IF NOT EXISTS launch_date date,
ADD COLUMN IF NOT EXISTS critical_deadlines text,
ADD COLUMN IF NOT EXISTS priority text,
ADD COLUMN IF NOT EXISTS acknowledgements_accepted boolean DEFAULT false;